# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- mast

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a26102de-a3b2-438d-9058-f5df86996588'
  imageRepository: 'adservice'
  containerRegistry: 'shubhamasr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/adservice/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
 name: "azureagent"

stages:
- stage: Build
  displayName: Build the app
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'


- stage: Push
  displayName: push to ACR
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'SHubhamASR'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'




- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'Microsoft Azure(1)(27208c8a-dc3a-43d9-a5e6-3eed81da070c)'
        azureResourceGroup: 'ShubhamDevOps-RG'
        kubernetesCluster: 'shubham-aks'
        namespace: 'default'
        manifests: '$(Build.SourcesDirectory)/kubernetes-manifests/cartservice.yaml'

