# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '80574239-82a8-40a1-b1ff-fdceac147129'
  imageRepository: 'frontend'
  containerRegistry: 'shubhamasr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/frontend/Dockerfile'
  tag: 'latest'

# Agent VM image name
pool:
  name: "azureagent"

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: 'SHubhamASR'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)

- stage: Push
  displayName: Push to ACR
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'SHubhamASR'
        repository: '$(imageRepository)'
        command: 'push'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'Microsoft Azure(7)(27208c8a-dc3a-43d9-a5e6-3eed81da070c)'
        azureResourceGroup: 'ShubhamDevOps-RG'
        kubernetesCluster: 'shubham-aks'
        namespace: 'default'
        manifests: '$(Build.SourcesDirectory)/kubernetes-manifests/frontend.yaml'
